version: '3.6'

networks:
  default:
    external:
      name: kafka_offshore

services:
  couchdb:
    image: couchdb:latest
    ports:
      - 5984:5984
    volumes:
      - ./.persist/couchdb:/opt/couchdb/data
    env_file:
      - ./env/couchdb

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: kos_zookeper
    env_file:
      - ./env/zookeeper

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    env_file:
      - ./env/kafka

  akhq:
    image: tchiotludo/akhq:latest
    container_name: kos_akhq
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8080:8080
    env_file:
      - ./env/akhq

  kafka-producer:
    image: kafka-backend-producer
    container_name: kos_backend-producer
    build:
      dockerfile: Dockerfile
      context: ./producer
    depends_on:
      - kafka
    ports:
      - 8000:8000
    env_file:
      - ./env/backend_producer

  kafka-consumer:
    image: kafka-worker-consumer
    container_name: kos_worker-consumer
    build:
      dockerfile: Dockerfile
      context: ./consumer
    depends_on:
      - kafka-producer
    env_file:
      - ./env/worker_consumer
