version: '3.6'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: kos_zookeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:latest
    container_name: kos_kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - ALLOW_ANONYMOUS_LOGIN=yes

  cmak:
    image: hlebalbau/kafka-manager:stable
    container_name: kos_cmak
    depends_on:
      - zookeeper
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=zookeeper:2181
      - APPLICATION_SECRET=random-secret
    command: -Dpidfile.path=/dev/null

  zeppelin:
    image: apache/zeppelin:0.9.0
    container_name: kos_zeppelin
    ports:
      - 8079:8080
    environment:
      ZEPPELIN_LOG_DIR: /logs
      ZEPPELIN_NOTEBOOK_DIR: /notebook
    volumes:
      - ./.tmp/logs:/logs
      - ./.data/kafka-poc/zeppelin/notebook:/notebook
      - ./.data/kafka-poc/zeppelin/conf:/zeppelin/conf
      - ./.data/kafka-poc/kafka-data:/data/kafka-poc/kafka-data

  spark-master:
    image: docker.io/bitnami/spark:3-debian-10
    container_name: kos_spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=spark-master
    ports:
      - 8080:8080
      - 7077:7077

  spark-worker:
    image: docker.io/bitnami/spark:3-debian-10
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=spark-worker
    ports:
      - 8081-8082:8081
    volumes:
      - ./.mnt/spark-apps:/opt/spark-apps
      - ./.mnt/spark-data:/opt/spark-data
