version: '3.6'

networks:
  bridge:
    driver: bridge

services:
  couchdb:
    image: couchdb:latest
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "1234abc"
    ports:
      - 5984:5984
    volumes:
      - ./.couchdb/data:/opt/couchdb/data
    networks:
      - bridge

  zookeeper:
    depends_on:
      - couchdb
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      bridge:
        aliases:
          - zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      # KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "flight:3:3"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:9092
      JMX_PORT: 9999
    networks:
      bridge:
        aliases:
          - kafka

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    environment:
      ZK_HOSTS: "zookeeper:32181"
    ports:
      - 9000:9000
    networks:
      - bridge

  kafka-producer:
    image: kafka-flink-producer
    build:
      dockerfile: Dockerfile
      context: ./producer
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      KAFKA_TOPIC: "flight"
      PRODUCER_INTERVAL: 10
    ports:
      - 8080:8080
    networks:
      - bridge

  kafka-consumer:
    image: kafka-flink-consumer
    build:
      dockerfile: Dockerfile
      context: ./consumer
    depends_on:
      - kafka-producer
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      KAFKA_TOPIC: "flight"
      COUCHDB_SERVER: "couchdb:5984"
    networks:
      - bridge
